spring:
  application:
    name: api_rest

  datasource:
    username: gustavo
    password: Simula14417
    url: jdbc:mysql://localhost/vollmed_api_rest
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
